export default [
  {
    id: 1,
    aisle_name: "water",
    aisle_number: "Aisle 1",
    item_name: "sparkling water",
  },
  {
    id: 2,
    aisle_name: "water",
    aisle_number: "Aisle 1",
    item_name: "coconut water",
  },
  {
    id: 3,
    aisle_name: "pop",
    aisle_number: "Aisle 1",
    item_name: "root beer",
  },
  {
    id: 4,
    aisle_name: "pop",
    aisle_number: "Aisle 1",
    item_name: "ginger ale",
  },
  {
    id: 5,
    aisle_name: "candy",
    aisle_number: "Aisle 1",
    item_name: "gummy bears",
  },
  {
    id: 6,
    aisle_name: "fresh fruits",
    aisle_number: "Front Left Area",
    item_name: "bananas",
  },
  {
    id: 7,
    aisle_name: "fresh fruits",
    aisle_number: "Front Left Area",
    item_name: "oranges",
  },
  {
    id: 8,
    aisle_name: "fresh vegetables",
    aisle_number: "Front Left Area",
    item_name: "spinach",
  },
  {
    id: 9,
    aisle_name: "fresh vegetables",
    aisle_number: "Front Left Area",
    item_name: "broccoli",
  },
  {
    id: 10,
    aisle_name: "mushroom & herbs",
    aisle_number: "Front Left Area",
    item_name: "button mushrooms",
  },
  {
    id: 11,
    aisle_name: "kombucha",
    aisle_number: "Front Left Area",
    item_name: "berry kombucha",
  },
  {
    id: 12,
    aisle_name: "packaged salads",
    aisle_number: "Front Left Area",
    item_name: "caesar salad mix",
  },
  {
    id: 13,
    aisle_name: "plant-based foods",
    aisle_number: "Front Left Area",
    item_name: "tofu",
  },
  {
    id: 14,
    aisle_name: "meats",
    aisle_number: "Back Left Area",
    item_name: "ribeye steak",
  },
  {
    id: 15,
    aisle_name: "meats",
    aisle_number: "Back Left Area",
    item_name: "bacon",
  },
  {
    id: 16,
    aisle_name: "seafood",
    aisle_number: "Back Left Area",
    item_name: "salmon fillets",
  },
  {
    id: 17,
    aisle_name: "seafood",
    aisle_number: "Back Left Area",
    item_name: "shrimp",
  },
  {
    id: 18,
    aisle_name: "sports drinks",
    aisle_number: "Aisle 1",
    item_name: "electrolyte drink",
  },
  {
    id: 19,
    aisle_name: "energy drinks",
    aisle_number: "Aisle 1",
    item_name: "energy shot",
  },
  {
    id: 20,
    aisle_name: "crackers",
    aisle_number: "Aisle 2",
    item_name: "cheddar crackers",
  },
  {
    id: 21,
    aisle_name: "popcorn",
    aisle_number: "Aisle 2",
    item_name: "buttered popcorn",
  },
  {
    id: 22,
    aisle_name: "nuts",
    aisle_number: "Aisle 2",
    item_name: "almonds",
  },
  {
    id: 23,
    aisle_name: "chips",
    aisle_number: "Aisle 2",
    item_name: "potato chips",
  },
  {
    id: 24,
    aisle_name: "tortilla chips",
    aisle_number: "Aisle 2",
    item_name: "blue corn chips",
  },
  {
    id: 25,
    aisle_name: "coffee",
    aisle_number: "Aisle 3",
    item_name: "espresso beans",
  },
  {
    id: 26,
    aisle_name: "hot chocolate",
    aisle_number: "Aisle 3",
    item_name: "instant cocoa",
  },
  {
    id: 27,
    aisle_name: "tea",
    aisle_number: "Aisle 3",
    item_name: "black tea",
  },
  {
    id: 28,
    aisle_name: "cookies",
    aisle_number: "Aisle 3",
    item_name: "chocolate chip cookies",
  },
  {
    id: 29,
    aisle_name: "snacking bars",
    aisle_number: "Aisle 3",
    item_name: "granola bars",
  },
  {
    id: 30,
    aisle_name: "kids juice",
    aisle_number: "Aisle 3",
    item_name: "apple juice boxes",
  },
  {
    id: 31,
    aisle_name: "cereal",
    aisle_number: "Aisle 4",
    item_name: "corn flakes",
  },
  {
    id: 32,
    aisle_name: "hot cereal",
    aisle_number: "Aisle 4",
    item_name: "instant oatmeal",
  },
  {
    id: 33,
    aisle_name: "pancakes",
    aisle_number: "Aisle 4",
    item_name: "maple syrup",
  },
  {
    id: 34,
    aisle_name: "seasonal",
    aisle_number: "Aisle 4",
    item_name: "holiday candy",
  },
  {
    id: 35,
    aisle_name: "baking",
    aisle_number: "Aisle 4",
    item_name: "baking soda",
  },
  {
    id: 36,
    aisle_name: "condiments",
    aisle_number: "Aisle 5",
    item_name: "mustard",
  },
  {
    id: 37,
    aisle_name: "pickles & olives",
    aisle_number: "Aisle 5",
    item_name: "dill pickles",
  },
  {
    id: 38,
    aisle_name: "spices",
    aisle_number: "Aisle 5",
    item_name: "black pepper",
  },
  {
    id: 39,
    aisle_name: "international",
    aisle_number: "Aisle 6",
    item_name: "curry paste",
  },
  {
    id: 40,
    aisle_name: "east asian",
    aisle_number: "Aisle 6",
    item_name: "rice noodles",
  },
  {
    id: 41,
    aisle_name: "south asian",
    aisle_number: "Aisle 6",
    item_name: "basmati rice",
  },
  {
    id: 42,
    aisle_name: "pasta",
    aisle_number: "Aisle 7",
    item_name: "penne",
  },
  {
    id: 43,
    aisle_name: "pasta sauce",
    aisle_number: "Aisle 7",
    item_name: "marinara sauce",
  },
  {
    id: 44,
    aisle_name: "soup",
    aisle_number: "Aisle 7",
    item_name: "chicken noodle soup",
  },
  {
    id: 45,
    aisle_name: "laundry",
    aisle_number: "Aisle 8",
    item_name: "fabric softener",
  },
  {
    id: 46,
    aisle_name: "cleaners",
    aisle_number: "Aisle 8",
    item_name: "all-purpose cleaner",
  },
  {
    id: 47,
    aisle_name: "candles",
    aisle_number: "Aisle 8",
    item_name: "unscented candles",
  },
  {
    id: 48,
    aisle_name: "natural snacks",
    aisle_number: "Aisle 9",
    item_name: "organic trail mix",
  },
  {
    id: 49,
    aisle_name: "natural beauty",
    aisle_number: "Aisle 11",
    item_name: "organic moisturizer",
  },
  {
    id: 50,
    aisle_name: "frozen desserts",
    aisle_number: "Aisle 14",
    item_name: "ice cream cake",
  },
  {
    id: 51,
    aisle_name: "candy",
    aisle_number: "Aisle 1",
    item_name: "marshmallows",
  },
  {
    id: 52,
    aisle_name: "meats",
    aisle_number: "Back Left Area",
    item_name: "hot dogs",
  },
  {
    id: 53,
    aisle_name: "plant-based foods",
    aisle_number: "Front Left Area",
    item_name: "veggie dogs",
  },
  {
    id: 54,
    aisle_name: "breads",
    aisle_number: "Right Area",
    item_name: "hot dog buns",
  }
];
